#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs

render_section () {
  local heading="$1" base="$2"
  [ -d "$base" ] || return 0

  local dirs
  dirs=$(find "$base" -type f -name '*.tf' -exec dirname {} \; | sort -u)
  [ -n "$dirs" ] || return 0

  echo "## ${heading}"
  echo

  while IFS= read -r dir; do
    name="${dir#"$base"/}"
    echo "### ${name}"
    echo
    terraform-docs markdown table "$dir"
    echo
  done <<< "$dirs"
}

{
  echo "# Terraform Documentation"
  echo
  echo "_Auto-generated by the Generate docs workflow. Do not edit by hand._"
  echo
  render_section "Environments" "environments"
  render_section "Module groups" "modulegroups"
  render_section "Modules" "modules"
} > docs/README.md
