name: Shared

on:
  workflow_call:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  checks:
    needs: lint
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/checks.yml
