name: Shared

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  checks:
    name: Checks
    needs: lint
    uses: ./.github/workflows/checks.yml
