name: Checks

on:
  workflow_call:

permissions: {}

jobs:
  validate:
    name: Terraform Validate
    permissions:
      contents: read
      actions: read # for private repo
      security-events: write
    strategy:
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: ./.github/workflows/tf-validate.yml
    with:
      environment: ${{ matrix.environment }}
  checkov-repo:
    name: Checkov Terraform (whole repo)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      # Checkov is run on created tfplan files during main branch trigger
      - name: Checkov Terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform
          soft_fail: false
