name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@a8664e3a0549367977f0cda990a34311835c87c0 #v12.3123.0
        name: Checkov Terraform
        with:
          directory: ./
          framework: terraform

  validate:
    permissions:
      contents: read
    needs: checkov
    strategy:
      max-parallel: 1 # run dev before test, and only if dev passes
      matrix:
        environment: [dev, test] # Add more envs as needed
    uses: ./.github/workflows/tf-validate.yml
    with:
      environment: ${{ matrix.environment }}
