name: Checks

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # every Monday 06:00 UTC

permissions: {}

jobs:
  validate:
    name: Terraform Validate
    permissions:
      contents: read
      actions: read # for private repo
    strategy:
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: ./.github/workflows/tf-validate.yml
    with:
      environment: ${{ matrix.environment }}
  checkov-terraform-static:
    name: Checkov Terraform (static)
    uses: ./.github/workflows/checkov.yml
    permissions:
      contents: read
      actions: read
      security-events: write
