name: Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx prettier --check "**/*.{json,yaml,yml,md}"

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: |
          tflint -f compact --recursive --chdir=modules --config="${{ github.workspace }}/.tflint.modules.hcl"
          tflint -f compact --recursive --chdir=modulegroups --config="${{ github.workspace }}/.tflint.modules.hcl"
          tflint -f compact --recursive --chdir=environments
