name: Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npx prettier --check "**/*.{json,yaml,yml,md}"

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2
      - name: Terraform fmt check
        run: terraform fmt -check -recursive

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef #v6.3.1
        with:
          tflint_version: latest
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run TFLint
        run: |
          tflint -f compact --recursive --chdir=modules --config="${{ github.workspace }}/.tflint.modules.hcl"
          tflint -f compact --recursive --chdir=modulegroups --config="${{ github.workspace }}/.tflint.modules.hcl"
          tflint -f compact --recursive --chdir=environments
