name: Main

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-apply
  cancel-in-progress: false

# main.yml
jobs:
  shared:
    name: Shared
    permissions:
      security-events: write
    uses: ./.github/workflows/_shared.yml

  plan:
    name: Terraform Plan
    needs: shared
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      security-events: write
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: ./.github/workflows/tf-plan.yml
    with:
      environment: ${{ matrix.environment }}
  apply:
    needs: plan
    name: Terraform Apply
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: true # Explictly prevent
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: ./.github/workflows/tf-apply.yml
    with:
      environment: ${{ matrix.environment }}
