name: Main

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: terraform-apply
  cancel-in-progress: false

# main.yml
jobs:
  checks:
    name: Checks
    permissions:
      contents: read
      actions: read # for private repo
      security-events: write
    uses: ./.github/workflows/checks.yml

  plan:
    name: Terraform Plan
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      security-events: write
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: ./.github/workflows/tf-plan.yml
    with:
      environment: ${{ matrix.environment }}

  apply:
    needs: [plan, checks]
    name: Terraform Apply
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: true # Explicitly prevent
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: ./.github/workflows/tf-apply.yml
    with:
      environment: ${{ matrix.environment }} #tf-plan.yml has plan_blob_name but using this deterministic for parallel changes
      plan_blob_name: ${{ github.repository }}/${{ matrix.environment }}/${{ github.run_id }}-${{ github.run_attempt }}/tfplan
