name: Main

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: terraform-apply
  cancel-in-progress: false

# main.yml
jobs:
  checks:
    name: Checks
    permissions:
      id-token: write
      checks: write
      contents: read
      actions: read # for private repo
      security-events: write
      pull-requests: write # For test reports
    uses: ./.github/workflows/checks.yml
  changes:
    runs-on: ubuntu-latest
    name: Terraform changed
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d #v4.0.3
        id: filter
        with:
          predicate-quantifier: every
          filters: |
            terraform:
              - "**/*.{tf,tfvars,hcl}"
              - "!**/tests/**"
              - "!**/*.tftest.hcl"
              - "!**/*.tfmock.hcl"
              - "!**/.terraform.lock.hcl"
  plan:
    name: Terraform Plan
    needs: [checks, changes]
    if: needs.changes.outputs.terraform == 'true'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      security-events: write
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: degero/azure-terraform/.github/workflows/tf-plan.yml@main
    with:
      environment: ${{ matrix.environment }}

  apply:
    needs: [plan]
    if: jobs.changes.outputs.terraform == 'true'
    name: Terraform Apply
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: true # Explicitly prevent
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    uses: degero/azure-terraform/.github/workflows/tf-apply.yml@main
    with:
      environment: ${{ matrix.environment }} #tf-plan.yml has plan_blob_name but using this deterministic for parallel changes
      plan_blob_name: ${{ github.repository }}/${{ matrix.environment }}/${{ github.run_id }}-${{ github.run_attempt }}/tfplan
