name: PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  shared:
    uses: ./.github/workflows/_shared.yml

  plan-pullrequest:
    permissions:
      id-token: write
    needs: shared
    uses: ./.github/workflows/tf-plan-apply.yml
    strategy:
      max-parallel: 1 # run dev before test, and only if dev passes
      matrix:
        include:
          - environment: dev
            noapply: true
          - environment: test
            noapply: true
    with:
      environment: ${{ matrix.environment }}
      noapply: ${{ matrix.noapply }}
    with:
      environment: ${{ matrix.environment }}
      noapply: ${{ matrix.noapply }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  doco:
    permissions:
      contents: write
    needs: plan-dev
    uses: ./.github/workflows/doco.yml
