name: PR

on:
  pull_request:
    branches: [main]
    paths:
      - environments
      - modules
      - modulegroups
      - tests

concurrency:
  group: terraform-plan-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  shared:
    uses: ./.github/workflows/_shared.yml
  doco:
    permissions:
      contents: write
    needs: plan
    uses: ./.github/workflows/doco.yml
  plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    needs: shared
    uses: ./.github/workflows/tf-plan.yml
    strategy:
      max-parallel: 1 # run dev before test, and only if dev passes
      matrix:
        environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}
    with:
      environment: ${{ matrix.environment }}
  apply: # apply to lowest environment only
    needs: plan
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tf-apply.yml
    with:
      environment: ${{ fromJSON(vars.TF_ENVIRONMENTS) }}[0]
