name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment
        type: string
        default: "dev"

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  WORKING_DIR: ./environments/${{ inputs.environment }}

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: "true"
      WORKING_DIR: ./environments/${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/tf-init
        with:
          working_directory: ${{ env.WORKING_DIR }}
      - name: Upload plan to blob storage
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          az storage blob upload \
            --auth-mode login \
            --account-name "${{ env.TFPLAN_STORAGE_ACCOUNT }}" \
            --container-name tfplans \
            --name "${{ inputs.environment }}/${{ github.run_id }}-${{ github.run_attempt }}/tfplan" \
            --file tfplan \
            --overwrite
      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
