name: Terraform Plan

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment
        type: string
        default: "dev"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./environments/${{ inputs.environment }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-init
        with:
          working_directory: ${{ env.WORKING_DIR }}
      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -var-file="${{ inputs.environment }}.tfvars" -out=tfplan
      - name: Post Plan
        if: always() && github.ref != 'refs/heads/master' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
        uses: robburger/terraform-pr-commenter@v1
        with:
          commenter_type: plan
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
      - name: Convert plan to JSON
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform show -json tfplan > tfplan.json
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}-tfplan
          path: ${{ env.WORKING_DIR }}/tfplan
      # If extra audit trail needed
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ inputs.environment }}-tfplan-json
      #     path: ${{ env.WORKING_DIR }}/tfplan.json
      - name: Checkov scan (plan)
        uses: bridgecrewio/checkov-action@master
        with:
          file: ${{ env.WORKING_DIR }}/tfplan.json
          framework: terraform_plan
          soft_fail: false
          output_format: cli,sarif # sarif enables GitHub code scanning integration
          output_file_path: console,results.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
