name: Terraform Unit Tests

on:
  push:

permissions:
  contents: read

jobs:
  terraform-unit-tests:
    name: Terraform Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
