name: Terraform Validate

on:
  workflow_call:
    inputs:
      environment:
        description: Validation environment
        type: string
        default: "dev"

jobs:
  tf-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      WORKING_DIR: ./environments/${{ inputs.environment }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_INPUT: 0
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/tf-init
        with:
          working_directory: ${{ env.WORKING_DIR }}
          no_backend: "true"
      - uses:
